/**
 * Help-view capability catalog — what Nova could support (not executable).
 * Evidence levels separate verified DAS docs from community recipes.
 */

import type { HotkeyCapabilityEntry } from './types';

export const HOTKEY_CAPABILITY_CATALOG: HotkeyCapabilityEntry[] = [
  {
    id: 'buy_fixed_shares',
    category: 'sizing',
    label: 'Buy / sell fixed shares',
    description: 'Literal Share=N with BUY=Send or SELL=Send. G3: Nova Actions buy/sell Ask±/Bid±.',
    example: 'ROUTE=LIMIT;Price=Ask+0.10;Share=100;TIF=DAY+;BUY=Send',
    evidence: 'das_verified',
    status: 'nova_active',
  },
  {
    id: 'share_pos',
    category: 'sizing',
    label: 'Trade full position (Share=Pos)',
    description: 'Size from current Montage position. G3: Nova Action exit_pos.',
    example: 'ROUTE=MARKET;Share=Pos;TIF=DAY+;SELL=Send',
    evidence: 'das_verified',
    status: 'nova_active',
  },
  {
    id: 'share_pos_pct',
    category: 'sizing',
    label: 'Sell / cover position percentage',
    description: 'Arithmetic like Share=Pos*0.5 — G3: Nova Action exit_pos_pct.',
    example: 'ROUTE=MARKET;Share=Pos*0.5;TIF=DAY+;SELL=Send',
    evidence: 'community_version_sensitive',
    status: 'nova_active',
    safetyNote: 'Validate rounding and short/long side before enabling.',
  },
  {
    id: 'bp_risk_sizing',
    category: 'sizing',
    label: 'Buying-power / risk-dollar sizing',
    description: 'Community DefShare/BP/risk formulas — not a single official command.',
    evidence: 'community_version_sensitive',
    status: 'backend_required',
  },
  {
    id: 'price_ask_bid',
    category: 'pricing',
    label: 'Ask / Bid with offset',
    description: 'Price=Ask+0.10 or Price=Bid-0.05. G3: requires live L2 top-of-book.',
    example: 'Price=Ask+0.10',
    evidence: 'das_verified',
    status: 'nova_active',
  },
  {
    id: 'price_avgcost',
    category: 'pricing',
    label: 'Average cost pricing',
    description: 'AvgCost / AvgCost2 in stops and targets.',
    example: 'STOPPRICE:AvgCost2-.20',
    evidence: 'das_verified',
    status: 'backend_required',
  },
  {
    id: 'order_mkt_lmt',
    category: 'order_type',
    label: 'Market and limit orders',
    description: 'ROUTE=MARKET / LIMIT (or broker smart routes).',
    evidence: 'das_verified',
    status: 'translatable_later',
  },
  {
    id: 'order_stops',
    category: 'order_type',
    label: 'Stop market / limit / trailing / range',
    description: 'DAS STOPTYPE variants including RANGE and TRAILING.',
    evidence: 'das_verified',
    status: 'backend_required',
  },
  {
    id: 'route_tif',
    category: 'route_tif',
    label: 'Route and TIF',
    description: 'DAY, DAY+, GTC, IOC, FOK, At Open/Close, NIGHT — broker/route dependent.',
    example: 'ROUTE=SMRTL;TIF=DAY+',
    evidence: 'das_verified',
    status: 'backend_required',
    safetyNote: 'Nova IBKR path uses SMART; direct ECN routes are DAS/broker-specific.',
  },
  {
    id: 'cancel_scopes',
    category: 'cancel',
    label: 'Cancel scopes',
    description:
      'Cancel all / same-symbol / buy-sell. G3: cancel_symbol (open symbol); cancel_and_exit cancels then flattens. Per-order Fill now is panel UI (not a hotkey).',
    example: 'CXL ALLSYMB',
    evidence: 'community_version_sensitive',
    status: 'nova_active',
  },
  {
    id: 'oto_trigger',
    category: 'linked_orders',
    label: 'OTO / TriggerOrder',
    description: 'Secondary order after primary fill (stop, limit, market, trailing, range).',
    example: 'BUY=Send;TriggerOrder=RT:STOP STOPTYPE:MARKET STOPPRICE:AvgCost2-.20 ACT:SELL QTY:POS TIF:DAY',
    evidence: 'das_verified',
    status: 'backend_required',
  },
  {
    id: 'oco',
    category: 'linked_orders',
    label: 'OCO (one-cancels-other)',
    description: 'Linked stop + target; Hotkey Builder “Order Cancel Order”.',
    evidence: 'das_verified',
    status: 'backend_required',
  },
  {
    id: 'reverse_flatten',
    category: 'intent',
    label: 'Send=Reverse / direction-neutral exit',
    description: 'Community flatten pattern; not the same as a true 2× flip.',
    example: 'Share=Pos;TIF=DAY+;Send=Reverse',
    evidence: 'community_version_sensitive',
    status: 'translatable_later',
  },
  {
    id: 'url_symb',
    category: 'workspace',
    label: 'Open symbol webpage',
    description: 'http://…/%SYMB% opens the active Montage symbol.',
    example: 'http://finance.yahoo.com/quote/%SYMB%',
    evidence: 'das_verified',
    status: 'das_ibkr_specific',
  },
  {
    id: 'montage_focus',
    category: 'workspace',
    label: 'Montage / window focus',
    description: 'SwitchTWnd, FocusWindow, GetWindowObj — version-sensitive.',
    example: 'SwitchTWnd',
    evidence: 'community_version_sensitive',
    status: 'das_ibkr_specific',
  },
  {
    id: 'share_adjust',
    category: 'sizing',
    label: 'Share size adjusters',
    description: 'Share=Share+100 style Montage field math.',
    example: 'Share=Share+100',
    evidence: 'das_verified',
    status: 'das_ibkr_specific',
  },
  {
    id: 'partial_then_be',
    category: 'composite',
    label: 'Partial exit then stop at breakeven',
    description: 'Cancel + sell % + re-place stop at AvgCost — composite recipe.',
    evidence: 'community_version_sensitive',
    status: 'backend_required',
  },
  {
    id: 'nova_automation',
    category: 'automation',
    label: 'Nova automation shortcuts',
    description: 'Approve/reject staged, Confirm/Signal, flatten prompt, kill switch — already active in Automation panel.',
    evidence: 'das_verified',
    status: 'nova_active',
    safetyNote: 'Separate from imported DAS scripts; not driven by .htk in this phase.',
  },
];
