/** Shared ticker fixtures for quote-panel unit tests. */
import type { TickerDetail } from '../types/ticker';

export function makeDetail(overrides: Partial<TickerDetail> = {}): TickerDetail {
  return {
    symbol: 'AAPL',
    mode: 'regular',
    avg_volume: 50_000_000,
    rel_volume: 1.25,
    rvol_5min: 2.1,
    volume_in_5min: 1_200_000,
    news: [],
    news_impact: null,
    asset: {
      name: 'Apple Inc',
      exchange: 'NASDAQ',
      tradable: true,
      shortable: true,
    },
    snapshot: {
      latest_trade: {
        price: 190.5,
        size: 100,
        exchange: 'Q',
        timestamp: '2026-07-15T14:30:00Z',
      },
      latest_quote: null,
      minute_bar: null,
      daily_bar: {
        open: 188,
        high: 191,
        low: 187,
        close: 190.5,
        volume: 40_000_000,
        trade_count: null,
        vwap: null,
        timestamp: null,
      },
      prev_daily_bar: {
        open: 185,
        high: 187,
        low: 184,
        close: 186,
        volume: 35_000_000,
        trade_count: null,
        vwap: null,
        timestamp: null,
      },
      prev_close: 186,
      session_close: null,
      session_prev_close: null,
    },
    fundamentals: {
      market_cap: 3e12,
      shares_outstanding: 15e9,
      float_shares: 15e9,
      short_interest: 100_000_000,
      short_ratio: null,
      short_percent_of_float: null,
      pe_ratio: null,
      forward_pe: null,
      eps: null,
      sector: 'Technology',
      industry: 'Consumer Electronics',
      fifty_two_week_high: 200,
      fifty_two_week_low: 150,
      dividend_yield: null,
      beta: null,
      earnings_date: '2026-08-01',
      recent_split: null,
    },
    ...overrides,
  };
}
