"""External dream bridges: Claude Code Auto Dream + OpenClaw MEMORY export.

Nova remains the Cursor agent OS. These bridges let sibling tools share memory
hygiene — they do **not** replace daddy/docs/tester specialists.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class BridgeReport:
    actions: list[str] = field(default_factory=list)
    files_touched: list[str] = field(default_factory=list)


def _rel(repo_root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(repo_root.resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def enable_claude_auto_dream(repo_root: Path, *, write: bool) -> BridgeReport:
    """Set autoDreamEnabled in .claude/settings.json (Claude Code)."""
    report = BridgeReport()
    path = repo_root / ".claude" / "settings.json"
    if not path.parent.is_dir():
        report.actions.append("claude: skipped (.claude/ missing)")
        return report

    data: dict = {}
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            report.actions.append("claude: settings.json invalid JSON — skipped")
            return report

    if data.get("autoDreamEnabled") is True:
        report.actions.append("claude: autoDreamEnabled already true")
        return report

    report.actions.append("claude: set autoDreamEnabled=true")
    if write:
        data["autoDreamEnabled"] = True
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
        report.files_touched.append(_rel(repo_root, path))
    return report


def export_openclaw_memory(
    repo_root: Path,
    staged_summaries: list[str],
    *,
    write: bool,
) -> BridgeReport:
    """Write an OpenClaw-compatible MEMORY.md snapshot for optional import.

    Does not install OpenClaw. Operators can copy/symlink this file into an
    OpenClaw workspace if they run that stack beside Nova.
    """
    report = BridgeReport()
    out = repo_root / ".cursor" / "agent-system" / "openclaw-MEMORY.md"
    lines = [
        "# MEMORY.md (Nova export for OpenClaw)",
        "",
        "Generated by `tools/agent_dream.py --bridges`.",
        "Nova Cursor agents remain authoritative; this is an interoperability snapshot.",
        "",
        "## Fleet signal (latest dream)",
        "",
    ]
    if staged_summaries:
        lines.extend(f"- {s}" for s in staged_summaries[:40])
    else:
        lines.append("- (no staged summaries)")
    lines.extend(
        [
            "",
            "## How to use with OpenClaw",
            "",
            "1. Install OpenClaw separately (do not vendor into Nova).",
            "2. Enable `memory-core` dreaming per OpenClaw docs.",
            "3. Copy or merge this file into the OpenClaw workspace `MEMORY.md`, "
            "or point a sync job at `.cursor/agent-system/openclaw-MEMORY.md`.",
            "4. Keep Nova `auto_live` NO-GO and IBKR gates — OpenClaw must not place Nova orders.",
            "",
        ]
    )
    body = "\n".join(lines)
    report.actions.append(f"openclaw: export MEMORY snapshot ({len(staged_summaries)} lines)")
    if write:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body, encoding="utf-8", newline="\n")
        report.files_touched.append(_rel(repo_root, out))
    return report
